config/routes.rb
Rails.application.routes.draw do
  post 'favorites/create'
  delete 'favorites/destroy'
  resources :recipes
  resources :sessions, only: [:new, :create]
  resources :users
  # resources :favorites, only: [:create, :destroy]
  # resources :recipes do
  #   put :favorite, on: :member
  # end
  get '/user_home', to: 'welcome#user_home'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  post '/logout' => 'sessions#destroy', as: 'logout' 
  
  root 'welcome#home'
  get '/about', to: 'welcome#about'
  get '/analytics', to: 'welcome#analytics'
  get '/quiz/play', to: 'quiz#play'
  get '/quiz', to: 'quiz#intro'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :style
    has_many :recipes_users
    has_many :users, through: :recipes_users
    has_many :favorites
    has_many :items
    has_many :ingredients, through: :items
    accepts_nested_attributes_for :ingredients, :allow_destroy => true
    
    validates :name, presence: true
    validates :name, uniqueness: { case_sensitive: true }
    validates :style, presence: { case_sensitive: true }
    validates :prep_time, presence:true
    #validates :rating, numericality: { only_integer: true }
    #validates_numericality_of :rating, less_than_or_equal_to: 10
    before_validation :uppercase_name
    # validates :prep_time, inclusion: {in: %w( min ), message: "Prep time must be in specified in minutes (min)" }
    validates :description, length: {minimum: 20}
    validates_associated :ingredients

    def ingredients_attributes=(ingredient_attributes)
        ingredient_attributes.values.each do |ingredient_attribute|
            if ingredient_attribute[:_destroy] == '1'
                ing = Ingredient.find_or_create_by(name: ingredient_attribute['name'], category: ingredient_attribute['category'])
                ing.delete
              else
                ing = Ingredient.find_or_create_by(name: ingredient_attribute['name'], category: ingredient_attribute['category'])
                self.ingredients << ing unless self.ingredients.include?(ing)
              end
            ingredient_attribute[:items_attributes].values.each do |item_attribute|
                #byebug
                if self.items.any?
                    self.items.each {|item| item.recipe_id == self.id && item.ingredient_id == ing.id}
                    item = self.items.select {|i| i.ingredient_id == ing.id && i.recipe_id == self.id}
                    nu_item = item.first
                    nu_item.quantity = item_attribute unless item_attribute.blank?
                    nu_item.save
                else
                    item = self.items.select {|i| i.ingredient_id == ing.id }
                    nu_item = item.first 
                    nu_item.quantity = item_attribute unless item_attribute.blank?
                    nu_item.save
                end
            end
        end
    end
    

    def uppercase_name
      name.upcase!
    end

    def self.average_calories
        cal =   self.all.collect do |recipe|
                    recipe.calories
                end
                
        tc = cal.sum 
        tr = Recipe.all.count
        ans = (tc / tr)
        ans
    end

    def self.average_rating
        rat = self.all.collect do |recipe|
                recipe.rating
              end
        
        ar = rat.sum 
        tr = Recipe.all.count
        ans = (ar / tr)
        ans
    end

    def self.average_prep_time
        prep = self.all.collect do |recipe|
                    recipe.prep_time.split('min')
                end
                #prep looks like: [["35 "], ["90 "], ["40 "]] 
        prep = prep.join.split
               #now prep looks like: ["35", "90", "40"] 

        prep.sum { |n| n.to_i } # turns each number to string then adds them together 
    end

    def self.all_recipes
        self.all.count 
    end


    def self.all_vegan_dishes
        self.all.collect do |dish|
            if dish.style_id == 35 #Style.where(name: 'VEGAN').id
                dish.name
            end
            
        end.compact
    end

    def self.all_vegetarian_dishes
        self.all.collect do |dish|
            if dish.style_id == 36
                dish.name
            end
            
        end.compact
    end

    def total_number_of_users
        User.all.count
    end


    def most_favorited_style
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :get_recipe, only: [:show, :edit, :update, :favorite, :destroy ]
    before_action :require_login

    def index
        @recipes = Recipe.all
    end 

    def new
        @recipe = Recipe.new
        @recipe.ingredients.build
    end
####################Original
    # def create
    #     @recipe = Recipe.new(recipe_params)
    #     #byebug
    #     if @recipe.save
    #         redirect_to recipe_path(@recipe)
    #     else
    #         render :new
    #     end
    # end
#######################
    def create
        @user = current_user
        #byebug
        @recipe = Recipe.new(recipe_params)
        if params[:add_ingredient]
        # add empty ingredient associated with @recipe
        @recipe.ingredients.build
        elsif params[:remove_ingredient]
        # nested model that have _destroy attribute = 1 automatically deleted by rails
    
        else
            if @recipe.valid?
                #byebug
                @recipe.save
                @user.recipes << @recipe
                flash[:notice] = "Successfully created recipe."
                return redirect_to recipe_path(@recipe) #and return
                #byebug 
            end
        end
        render :new
    end


    def edit
    end

    def update
        if params[:add_ingredient]
            unless params[:recipe][:ingredients_arrtibutes].blank?
                for attribute in params[:recipe][:ingredients_attributes]
                    @recipe.ingredients.build(attribute.last.except(:_destroy)) unless attribute.last.has_key?(:id)
                end
            end
            @recipe.ingredients.build
        elsif params[:remove_ingredient]
            
            removed_ingredients = []
            recipe_params[:ingredients_attributes].each { |i, att| removed_ingredients << att[:id] if (att[:id] && att[:_destroy].to_i == 1) }
            Ingredient.delete(removed_ingredients)
            flash[:notice] = "Ingredients removed."
            #for attribute in params[:recipe][:ingredients_attributes]
             #   @recipe.ingredients.build(attribute.last.except(:_destroy)) if (!attribute.last.has_key?(:id) && attribute.last[:_destroy].to_i == 0)
            #end
        else
            if @recipe.valid? 
                @recipe.update_attributes(recipe_params)
                flash[:notice] = "Successfully updated recipe."
                #byebug
                return redirect_to recipe_path(@recipe)
            end
        end
        render :edit       
    end

    # def favorite 
    #     fave = params[:fave]
    #     if fave == "favorite"
    #         current_user.favorites << @recipe
    #         flash[:notice] = "Added to favorites!"
    #         redirect_to recipe_path(@recipe)
    #     elsif fave == "unfavorite"
    #         current_user.fav.delete(@recipe)
    #         flash[:notice] = "Removed from favorites"
    #         redirect_to recipe_path(@recipe)
    #     end
    # end

    def show
    end 

    def destroy 
        @recipe.items.destroy_all
        @recipe.destroy
        flash[:notice] = "Successfully deleted recipe."
        redirect_to recipes_path 
    end


    private
    
     def recipe_params
        params.require(:recipe).permit(
            :id, 
            :name, 
            :calories, 
            :description, 
            :prep_time, 
            :style_id, 
            :rating,
            :fave, 
            :add_ingredient, 
            :remove_ingredient, 
            ingredients_attributes: [
            :name,
            :category,
            :id,
            :_destroy,
            items_attributes: [:id, :quantity, :recipe_id, :ingredient_id, :_destroy]])
     end

     def get_recipe
        @recipe = Recipe.find(params[:id])
     end

     
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@recipe.errors.count, "error") %>
      kept this post from being saved:
    </h2>
 
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :Name %>
<%= f.text_field :name %><br>
<br>
<%= f.label :Calories %>
<%= f.text_field :calories %><br>
<br>
<%= f.label :Prep_time %>
<%= f.text_field :prep_time %><br>
<br>
<%= f.label :Description %><br>
<%= f.text_area :description%><br>
<br>
<%= f.label :Dish_Style %>
<%= f.collection_select :style_id, Style.all, :id, :name, prompt: true %><br>
<%= f.label :Rating %>
<%= f.text_field :rating %><br>
<br>
<%= f.label :Ingredients %>
<%= f.fields_for :ingredients do |ingred|  %>
    <br>
    <br>
    <%= render 'ingredient_fields', :f => ingred %>
<% end %>
<div class="links">
<%= link_to_add_association 'add ingredient', f, :ingredients, class: "btn btn-default add_button" %><br>
</div>

<%= f.submit %>


<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class='nested-fields'>
<%= f.label :name %><br>
<%= f.text_field :name %><br>
<%= f.label :category %><br>
<%= f.text_field :category %><br>
<%= f.fields_for :items_attributes do |item_a|  %>
        <%= render 'item_attr', :f => item_a, partial: 'item_attr' %>
<% end %>
<%= link_to_remove_association "remove ingredient", f %><br><br><br>
</div>

app/views/recipes/_item_attr.html.erb
<%= f.label :quantity %><br>
<%= f.text_field :quantity %><br>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<div id = "new recipe form">
<%= render 'form' %>
</div>

app/views/recipes/index.html.erb
<br><br>
<div class="center" align="center" style="padding: 50px;">
<h2>All Recipes</h2>
<table style="text-align: center;">
    <tr>
        <th></th>
    </tr>
    <tr>
    <td>
    <dl>
    <% @recipes.each do |recipe| %>
        <li><%= link_to recipe.name, recipe_path(recipe)  %></li>
    <% end %>
    </td>
    </tr>
</dl>
</table>
<br>
<%= button_to "Create Recipe", new_recipe_path, :method => :get %>
</div>

app/views/recipes/new.html.erb
<% stylesheet_link_tag '/assets/stylesheets/application.css' %>
<h1>Create a Recipe!</h1>
<div id = "new recipe form">
<%= render 'form' %>
</div>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<div align="center">
<h6>submitted by: <%= @recipe.users.first.email %></h6>
<h5>Calories</h5>
<%= @recipe.calories %><br><br>
<h5>Prep Time</h5>
<%= @recipe.prep_time %><br><br>
<h5>Description</h5>
<%= @recipe.description %><br><br>
<h5>Dish Style</h5><br><br>
<%= @recipe.style.name %><br><br>
</div>
<div align="center" style="padding: 50px;">
<h5>Ingredients</h5>
<table style="text-align: center;">

<table>
<tr><th>ingredient</th><th>amount</th><th>type</th></tr>
<% @recipe.ingredients.each do |ing| %>
    <tr><td><%= ing.name %></td>
    
    <td><%= @recipe.items.find_by(ingredient: ing).quantity %></td>
    <td><%= ing.category %></td></tr>
    
    <% #byebug %>
    
<% end %>
</table>
</div>
<br>
<br>
<table>
<tr><th>
<div id="edit_button">
<%= button_to "Edit Recipe", edit_recipe_path(@recipe), :method => :get, :class => "button-clear" %>
</div>
</th>
<th>
<div id="delete_button">
<%= button_to "Delete Recipe", recipe_path(@recipe), :method => :delete, :class => "button-clear" %>
</div>
</th>
<th>
<div id="add_button">
<%= button_to 'Add to favorites', favorites_create_path(recipe_id: @recipe), method: :post, :class => "button-clear" %>
</div>
</th>
<th>
<div id="remove_button">
<%= button_to 'Remove from favorites', favorites_destroy_path(recipe_id: @recipe), method: :delete, :class => "button-clear" %>
</div>
</th>
</tr>
</table>