config/routes.rb
Rails.application.routes.draw do
  post 'favorites/create'
  delete 'favorites/destroy'
  resources :recipes
  resources :sessions, only: [:new, :create]
  resources :users
  # resources :favorites, only: [:create, :destroy]
  # resources :recipes do
  #   put :favorite, on: :member
  # end
  get '/user_home', to: 'welcome#user_home'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  post '/logout' => 'sessions#destroy', as: 'logout' 
  
  root 'welcome#home'
  get '/about', to: 'welcome#about'
  get '/analytics', to: 'welcome#analytics'
  get '/quiz/play', to: 'quiz#play'
  get '/quiz', to: 'quiz#intro'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :require_login, only: [:user_home]
    def home
    end

    def about 
    end

    def user_home
        @user = current_user
    end

    def analytics
    end
end

app/views/welcome/about.html.erb
<h1>What is Crecipe?</h1>
<div align="center">
<img src="https://thumbs.dreamstime.com/b/ingredients-cooking-pizza-pasta-dough-heart-shape-ingredients-cooking-pizza-pasta-dough-heart-shape-109554030.jpg" alt="cooking photo">
<h5>Founded by Allene Norton and Cedric Patton, Crecipe is a uniquely innovative way for cooking enthusiasts to explore original recipe ideas, rate and add them to your favorites. And users can even create and share their own recipe creations!<h5/>
<br>
<h5>With Crecipe, you can hone your cooking skills and release the inner chef within you! Wanna become the next Bobby Flay or Gordan Ramsey? Well you should probably go to a culinary school...but Crecipe is a great start!  </h5>
</div>

app/views/welcome/analytics.html.erb
<h1>Analytics</h1>

<div align="center">
<h3>Averages</h3>

<h4>Average Recipe Rating</h4>
<p><%= Recipe.average_rating %> stars</p>

<h4>Average Recipe Prep Time</h4>
<p><%= Recipe.average_prep_time %> min</p>
 
 <h4>Average Recipe Calories</h4>
<p><%= Recipe.average_calories %> calories</p>

<h3>Highlights</h3>

<h4>Total Recipes</h4>
<p><%=link_to Recipe.all_recipes, recipes_path %></p>



<h3>Preferences</h3>

<h4>Vegan recipes</h4>
<dl>
 <% Recipe.all_vegan_dishes.each do |vegan| %> 
  
    <li><%=link_to vegan, recipe_path(Recipe.where(name: vegan).ids) %></li> 
    
 <% end %>
 </dl>

 <h4>Vegetarian recipes</h4>
<dl>
 <% Recipe.all_vegetarian_dishes.each do |veggie| %> 
    <li><%=link_to veggie, recipe_path(Recipe.where(name: veggie).ids) %></li>   
 <% end %>
 </dl>
<h4> Recipes with rice</h4>
<dl>
 <% Ingredient.all_rice_dishes.each do |recipe| %> 
    <li><%=link_to recipe.name, recipe_path(recipe) %></li>  
 <% end %>
</dl>
<h4> Recipes with chicken</h4>
<dl>
 <% Ingredient.all_chicken_dishes.each do |recipe| %> 
    <li><%=link_to recipe.name, recipe_path(recipe) %></li>  
 <% end %>
</dl>
<h4> Recipes with pasta</h4>
<dl>
 <% Ingredient.all_pasta_dishes.each do |recipe| %> 
    <li><%=link_to recipe.name, recipe_path(recipe) %></li>  
 <% end %>
</dl>

app/views/welcome/home.html.erb
<div class="logo" align="center">
<%= image_tag("crecipe_logo.png", :alt => "crecipe logo") %>
</div>

app/views/welcome/user_home.html.erb
<div class="center" align="center" style="padding: 50px;">
<table style="text-align: center;">
  <tr>
    <th><h3>My Recipes</h3></th>
    <th><h3>Favorites</h3></th>
  </tr>
  <tr>
    <td>
    <dl>
    <% @user.recipes.each do |recipe| %>
      <li><%= link_to recipe.name, recipe_path(recipe) %></li>
    <% end %>
    </dl>
    </td>
    <td>
      <dl>
        <% current_user.favorites.each do |fav| %>
          <li><%= link_to fav.recipe.name, recipe_path(fav.recipe) %> </li>
        <% end %>
      </dl>
    </td>
  </tr>
  </table>
</div>
<!--<h2>My Recipes</h2>
<% @user.recipes.each do |recipe| %>
  <%= link_to recipe.name, recipe_path(recipe) %>
<% end %>
<br><br>
<h2>Favorites</h2>
<ul>
<% current_user.favorites.each do |fav| %>
    <li>Name: <%= fav.recipe.name %> </li>
    </ul>
<% end %>
</table>
<br><br>
<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>-->